apiVersion: v1
kind: ConfigMap
metadata:
  name: tfe-nginx-template
  namespace: {{ .Release.Namespace }}
data:
  terraform-enterprise.conf.tmpl: |
{{ .Files.Get "custom-nginx-template-v1.conf" | indent 4 }}
